### ISSUE TITLE
Feature Request: Add common "meat" tags from other mods to the Charnel Compactor recipe list

### ISSUE THREAD

**Issue by Derpford** [MeatWheeze/NeepMeat#11]
Some examples:
- [Chest Cavity](https://www.curseforge.com/minecraft/mc-mods/chest-cavity)'s `salvageable_human_organ_meat`, `salvageable_animal_organ_meat`, `salvageable_rotten_flesh` and `rotten_food`
- The `c:raw_meats` tag, which coincidentally includes a bunch of Chest Cavity's non-organ raw meat items

Possible concerns:
- Farmer's Delight would allow doubling output from several kinds of meat, since you can cut pork, beef, chicken, and fish to get better output. However, IMO this is perfectly acceptable, as you're already expected to automate production of various meat products, you're incentivized to go straight to dumping the whole animal into a grinder, and frankly, using your butchering skills to make meat production more efficient seems like it fits right into the thematic/aesthetic style of this mod.

**Comment by Derpford** [comment]
...another thing that would make a lot of sense is adding meat ingots to the Charnel Compactor. It would at least dramatically simplify making a farm production facility. Then again, maybe having to have a second animal pen to produce meat and blood the hard way is part of the point...

[Edit] I have since realized that meat ingots can be pressed out of liquid meat, and that the Death Blades make liquid meat accessible much earlier than I expected. D'oh.

**Comment by MeatWheeze** [comment]
These are good ideas. I'll add the Chest Cavity tags. I think the Charnel Compactor uses `c:raw_meat` by default.

Apparently `neepmeat:charnel_substrate` is unused. Silly me.
