### ISSUE TITLE
Feature Request: Vascular Source Converter redstone control

### ISSUE THREAD

**Issue by Derpford** [MeatWheeze/NeepMeat#16]
Right now, the only apparent way to control whether power is running to a device in a Vascular Network is to shut off fuel to a Heart Machine.

I propose adding redstone control to the VSC. This would come with a second input field in the UI--one would be labeled with a lit redstone torch, the other with an unlit RS torch, to indicate that one is active when power is on and one is active when power is off. This would allow for disabling individual motors or heaters to funnel power away from inactive devices, or enabling a "high power" mode when available fuel is higher than normal.

**Comment by MeatWheeze** [comment]
This is a good addition. I've implemented it with a texture change indicating whether the VSC is active rather than a GUI element.
