### ISSUE TITLE
Feature Request: JEI Compat

### ISSUE THREAD

**Issue by nothingtown** [MeatWheeze/NeepMeat#24]
Hi! My friends and I adore your mod and have integrated it into our Minecraft server; we were wondering if you have any plans to add JEI compatibility like you did for REI? It would be pretty helpful! :)

**Comment by MeatWheeze** [comment]
Maintaining parity for both EMI and REI integrations across two different Minecraft versions is already quite time-consuming, so I will not be adding integration for JEI in the near future.  Sorry about this.

**Comment by unilock** [comment]
For the record, EMI can load both EMI and JEI plugins from mods if it's installed alongside JEI. (it will replace JEI's UI)
