### ISSUE TITLE
Crash loading into a world

### ISSUE THREAD

**Issue by Abalieno** [MeatWheeze/NeepMeat#4]
0.2.5-alpha+1.19.2

0.2.4 seems to work.

May be due to Create now on Fabric requiring me to use a newer version of porting lib? porting_lib-2.1.1171+1.19.2

[crash-2024-01-10_10.36.59-client.txt](https://github.com/MeatWheeze/NeepMeat/files/13885839/crash-2024-01-10_10.36.59-client.txt)

**Comment by MeatWheeze** [comment]
Create's bundled version of Flywheel (0.6.9-6) is older than NeepMeat's (0.6.10-8) and the newer one is being prioritised. The signature of VirtualRenderWorld::new must have changed between these versions, which is causing the crash.

It seems to be fixed by downgrading Flywheel.
