### ISSUE TITLE
Ticking block entity Pedestal crash

### ISSUE THREAD

**Issue by RustVEVO** [MeatWheeze/NeepMeat#6]
Hey there! Big fan of your mod. The eldritch harvesting biopunk sort of thing isn't anything I've seen done before. You should totally make a Discord.
But, anyways, onto the issue. We've been planning on using your mod in a multiplayer mod server, but, whenever I try to connect a pedestal to an integrator via data cables, the world instantly crashes and becomes entirely unusable. I've tested it on a world with only NEEPmeat and it worked out, so, it isn't an issue with your mod. But I thought I'd notify you on an incompatibility. And tell you that I enjoy your work.
Here's the crash report.

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-02-03 12:20:26
Description: Ticking block entity

java.lang.UnsupportedOperationException: This object is not a real inventory
	at com.neep.meatlib.recipe.ImplementedRecipe$DummyInventory.getItems(ImplementedRecipe.java:39)
	at com.neep.meatlib.inventory.ImplementedInventory.method_5439(ImplementedInventory.java:28)
	at net.minecraft.class_1863.calcHash(class_1863.java:777)
	at net.minecraft.class_1863.handler$ghm000$recipeessentials$onGetRecipe(class_1863.java:549)
	at net.minecraft.class_1863.method_8132(class_1863.java)
	at com.neep.neepmeat.machine.pedestal.PedestalBlockEntity$RecipeBehaviour.update(PedestalBlockEntity.java:184)
	at com.neep.neepmeat.machine.pedestal.PedestalBlockEntity.tick(PedestalBlockEntity.java:124)
	at com.neep.neepmeat.machine.pedestal.PedestalBlock.lambda$getTicker$0(PedestalBlock.java:118)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:842)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.neep.meatlib.recipe.ImplementedRecipe$DummyInventory.getItems(ImplementedRecipe.java:39)
	at com.neep.meatlib.inventory.ImplementedInventory.method_5439(ImplementedInventory.java:28)
	at net.minecraft.class_1863.calcHash(class_1863.java:777)
	at net.minecraft.class_1863.handler$ghm000$recipeessentials$onGetRecipe(class_1863.java:549)
	at net.minecraft.class_1863.method_8132(class_1863.java)
	at com.neep.neepmeat.machine.pedestal.PedestalBlockEntity$RecipeBehaviour.update(PedestalBlockEntity.java:184)
	at com.neep.neepmeat.machine.pedestal.PedestalBlockEntity.tick(PedestalBlockEntity.java:124)
	at com.neep.neepmeat.machine.pedestal.PedestalBlock.lambda$getTicker$0(PedestalBlock.java:118)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)

-- Block entity being ticked --
Details:
	Name: neepmeat:pedestal // com.neep.neepmeat.machine.pedestal.PedestalBlockEntity
	Block: Block{neepmeat:pedestal}
	Block location: World: (11,-60,2), Section: (at 11,4,2 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Block: Block{neepmeat:pedestal}
	Block location: World: (11,-60,2), Section: (at 11,4,2 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:842)

-- Affected level --
Details:
	All players: 1 total; [class_3222['RustVEVO'/550, l='ServerLevel[New World]', x=9.77, y=-60.00, z=1.69]]
	Chunk stats: 8649
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2791 game time, 2791 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 143789 (now: false), thunder time: 72626 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:842)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.9, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 4023122656 bytes (3836 MiB) / 7969177600 bytes (7600 MiB) up to 10468982784 bytes (9984 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600G with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.89
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: USB Mobile Monitor Virtual Display
	Graphics card #0 vendor: Amyuni
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=2.0.0.1
	Graphics card #1 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2489
	Graphics card #1 versionInfo: DriverVersion=31.0.15.3770
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37704.71
	Virtual memory used (MB): 31371.72
	Swap memory total (MB): 21735.64
	Swap memory used (MB): 1916.89
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx9984m
	Fabric Mods: 
		altorigingui: Alternate Origin GUI 1.0.1
		animated_guns: Simple Animated Guns 1.2
		architectury: Architectury 6.5.85
		armorsoundtweak: Armor Sound Tweak 6.0.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		audioplayer: AudioPlayer 1.19.2-1.8.7
			admiral: Admiral 0.4.4+1.19.2
		autotag-convention: AutoTag Convention 2.0.0+1.19
			autotag: AutoTag 2.0.0+1.19
		badoptimizations: BadOptimizations 1.6.3
		bbs: Better Block Sounds ${version}
		bcc: BetterCompatibilityChecker 2.0.2-build.16+mc1.19.1
		betterchunkloading: Better chunk loading mod 1.19.2-2.3
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.2
			org_reflections_reflections: reflections 0.10.2
		betterendisland: YUNG's Better End Island 1.19.2-Fabric-1.0
		betterjungletemples: YUNG's Better Jungle Temples 1.19.2-Fabric-1.0.1
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		betterthirdperson: Better Third Person 1.9.0
		bewitchment: Bewitchment 1.19-7
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			impersonate: Impersonate 2.8.0
			playerabilitylib: Pal 1.6.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
			terraform-wood-api-v1: Terraform Wood API (v1) 4.2.0
		blockus: Blockus 2.5.11+1.19.2
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.8-1.19.2
			maelstrom_library: Maelstrom Library 1.3.1-1.19.2
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		bot: Base Origins Tweaks 1.0.0
		bsvsb: Better Sodium Video Settings Button 3.0.2
		butcherymod: Butchery Mod 0.1.1.19.2
		bwncr: Bad Wither No Cookie Reloaded 3.14.1
		cakedelight: Cake Delight 1.19.2-v2.0.2
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		carryon: Carry On 2.1.1.22
		casualness_delight: Casualness Delight Fabric 1.19.2-0.2a
		catsexpanded: Cats Expanded 1.3.0+1.19.2
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charmofundying: Charm of Undying 6.2.1+1.19.2
		chunksending: Chunksending Mod 1.19.2-2.8
		cloth-config: Cloth Config v8 8.3.115
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+14
		coffee_delight: Coffee Delight 1.4
		comforts: Comforts 6.0.7+1.19.2
			spectrelib: SpectreLib 0.12.8+1.19.2
		computercraft: CC: Restitched 1.101.2
			io_netty_netty-codec-http: netty-codec-http 4.1.77.Final
			org_squiddev_cobalt: Cobalt 0.5.5
		connectivity: Connectivity Mod 1.19.2-4.5
		consularsorigins: Consulars Origins 1.8.0
		controlling: Controlling For Fabric 10.0+7
		copperandtuffbackport: CopperandTuffBackport 1.1
		corndelight: Corn Delight 1.0.4
		culturaldelights: Cultural Delights Fabric 0.14.10+1.19.2
		cupboard: cupboard 1.19.2-2.3
		customizableelytra: Customizable Elytra 1.6.4-1.19
		debugify: Debugify 2.8.0
		deeperdarker: Deeper and Darker 1.2.5
			customportalapi: Custom Portal Api 0.0.1-beta63-1.19.X
		dehydration: Dehydration 1.3.4
		dragonfight: Dragonfight Mod 1.19.2-4.1
		eldritch_mobs: EldritchMobs 1.13.2
			polymer: Polymer (Core) 0.2.28+1.19.2
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
				polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.0.3+1.19.2
			polymer-blocks-ext: Polymer Blocks 0.1.0-alpha.9+1.19.2
			server_translations_api: Server Translations API 1.4.18+1.19.2
		elytraslot: Elytra Slot 6.1.1+1.19.2
		emotecraft: Emotecraft 2.2.5
			bendy-lib: Bendy api 2.1.2
			player-animator: Player Animator 0.3.5
		ends_delight: End's Delight 1.19.2-1.0
		environmentz: EnvironmentZ 2.0.5
			satin: Satin 1.9.0
		expanded_armor_enchanting: Expanded Armor Enchanting 1.0.3
		expandeddelight: Expanded Delight 0.2.5.2
		expandedenderchest: Expanded Enderchest 1.0.0+1.19.2
		extra_classes_origins: Extra Classes - Origins 1.0.0
		extraextrakeybinds: More of ThatRobins Extra Origins Keybinds 0.4.0+1.17-1.19.2
		fabric-api: Fabric API 0.77.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.42+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.9+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.12+def3f86d90
			fabric-networking-v0: Fabric Networking (v0) 0.3.29+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.1.0+ee641e7390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.2+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.33+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.25+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.28+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.13.0+526f2c6790
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.8+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.6
			mixinextras: MixinExtras 0.3.2
		farmersdelight: Farmer's Delight 1.19.2-1.3.10.2
		farmersknives: Farmer's Knives 2.4.1
		farmersrespite: Farmer's Respite 2.2.5
			porting_lib: Porting Lib 2.1.815+1.19.2
				forge_tags: Porting Lib Tags 3.0
				mm: Manningham Mills 2.3
				porting_lib_accessors: Porting Lib Accessors 2.1.815+1.19.2
				porting_lib_attributes: Porting Lib Attributes 2.1.815+1.19.2
				porting_lib_base: Porting Lib Base 2.1.815+1.19.2
				porting_lib_common: Porting Lib Common 2.1.815+1.19.2
				porting_lib_constants: Porting Lib Constants 2.1.815+1.19.2
				porting_lib_entity: Porting Lib Entity 2.1.815+1.19.2
				porting_lib_extensions: Porting Lib Extensions 2.1.815+1.19.2
				porting_lib_fake_players: Porting Lib Fake Players 2.1.815+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.815+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.815+1.19.2
				porting_lib_model_loader: Porting Lib Model Loader 2.1.815+1.19.2
				porting_lib_models: Porting Lib Models 2.1.815+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.815+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.815+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.815+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
		fdjei: Just Enough Farmer's Recipes 1.0.1
		festive_delight: Festive Delight 1.0.0
		forgeconfigapiport: Forge Config API Port 4.2.11
		friendsandfoes: Friends&Foes 2.0.7
		gardens_of_the_dead: Gardens of the Dead 2.0.0
			terrablender: TerraBlender 2.0.1.130
		geckolib3: Geckolib 3.1.40
			com_eliotlash_mclib_mclib: mclib 20
		haema: Haema 1.10.4+1.19
		halfdoors: Half Doors 1.3.9+1.19.x
		handcrafted: Handcrafted 2.0.6
		immersive_paintings: Immersive Paintings 0.6.7+1.19.2
		indium: Indium 1.0.9+mc1.19.2
		inventorysorter: Inventory Sorter 1.8.10-1.19
			kyrptconfig: Kyrpt Config 1.4.14-1.19
		iris: Iris 1.6.11
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: Java HotSpot(TM) 64-Bit Server VM 17
		jei: Just Enough Items 11.6.0.1018
		journeymap: Journeymap 5.9.7
			journeymap-api-fabric: JourneyMap API 1.19.1-1.9-fabric-SNAPSHOT
		lambdynlights: LambDynamicLights 2.2.0+1.19.2
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.1.0+1.19.2
		laserbridges: LaserBridges 1.19.2-1
		last_of_us: Last Of Us 1.0.0
		limitedchunks: Limited Chunkloading Mod 1.19.2-3.8
		limitedlives: Limited Lives 1.0.1
		lithium: Lithium 0.11.1
		lmft: Load My F***ing Tags 1.0.2+1.19
		loadmyresources: Load My Resources 1.0.4
		logbegone: Log Begone 1.0.6
		maxhealthfix: MaxHealthFix 8.0.2
		mca: Minecraft Comes Alive 7.5.12+1.19.2
		mcwfences: Macaw's Fences and Walls 1.1.0
		mcwfurnitures: Macaw's Furniture 3.2.2
		mcwlights: Macaw's Lights and Lamps 1.0.6
		mcwtrpdoors: Macaw's Trapdoors 1.1.2
		mcwwindows: Macaw's Windows 2.2.0
		memorysettings: Memorysettings Mod 1.19.2-5.3
		midnightlib: MidnightLib 1.0.0
		minecarttweaks: Cammie's Minecart Tweaks 1.7
		minecraft: Minecraft 1.19.2
		modern_industrialization: Modern Industrialization 1.6.18
			magna: Magna 1.8.0-1.19
				omega-config: OmegaConfig 1.0.8
			noindium: No Indium? 1.1.0+1.19
			team_reborn_energy: Energy 2.3.0
		movingelevators: Moving Elevators 1.4.5
		neepmeat: NEEPMeat 0.2.8-alpha+1.19.2
			flywheel: Flywheel 0.6.9-6
			myron-neepmeat: Myron-NEEPMeat 1.6.3+1.19.2
		nethersdelight: Nether's Delight 1.0.1
			disable_custom_worlds_advice: Disable Custom Worlds Advice 3.0
		notenoughanimations: NotEnoughAnimations 1.7.0
		origins: Origins 1.7.1
			apoli: Apoli 2.6.1
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
		origins-classes: Origins: Classes 1.4.0
		patchouli: Patchouli 1.19.2-77-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.7.12+1.14.4-1.20.4
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		playerplates: Player Plates 2.0.0-build.19+mc1.19.2
		polymer-all: Polymer (Packed) 0.2.28+1.19.2
		protectmobsfromdaylight: Protect Mobs From Daylight 1.0.1
		puffish_skills: Pufferfish's Skills 0.10.0
		puzzleslib: Puzzles Lib 4.4.3
		ratsmischief: Rat's Mischief 1.4.0
		reborncore: Reborn Core 5.4.0
		recipeessentials: recipeessentials Mod 1.19.2-3.2
		redstonepen: Redstone Pen 1.2.18
		resourcefullib: Resourceful Lib 1.1.24
		rodentorigins: Rodent Origins 1.0-SNAPSHOT
		seasons: Fabric Seasons 2.3+1.19
		seasonsdelightcompat: Fabric Seasons: Delight Compat 1.0-1.3.9
		seasonsextras: Fabric Seasons: Extras 1.2-BETA+1.19
		showmeyourskin: Show Me Your Skin! 1.6.3+1.19.2
			cicada: CICADA 0.4.0
		shulkerboxslot: Shulker Box Slot 5.0.0-beta.1+1.19.2
		skinlayers3d: 3d-Skin-Layers 1.6.2
		skunk: Wildlife expanded: Skunk 2.0.2
		smoothchunk: Smooth chunk save Mod 1.19.2-3.5
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		solar_apocalypse: Solar Apocalypse 1.4.1
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.3.1
		starlight: Starlight 1.1.1+fabric.ae22326
		stoneholm: Stoneholm 1.4.4
		structureessentials: Structure Essentials Mod 1.19.2-3.2
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.16
		toofast: TooFast 1.0.0
		trinkets: Trinkets 3.4.2
		twigs: Twigs 3.0.0
		underground_bunkers: Underground Bunkers 1.0.3
		universal-graves: Universal Graves 2.1.3+1.19.2
			common-protection-api: Common Protection API 1.0.0
			hologram-api: Hologram API 0.2.2+1.19
			placeholder-api: Placeholder API 2.0.0-pre.1+1.19.2
			sgui: sgui 1.1.5+1.19.1
		visualworkbench: Visual Workbench 4.2.4
		voicechat: Simple Voice Chat 1.19.2-2.4.32
		watching: From The Fog 1.9.1
		yet-another-config-lib: YetAnotherConfigLib 2.2.0-for-1.19.2
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.10
			org_javassist_javassist: javassist 3.28.0-GA
		yungsbridges: YUNG's Bridges 1.19.2-Fabric-3.1.0
		yungsextras: YUNG's Extras 1.19.2-Fabric-3.1.0
		zombie-jerky: Zombie Jerky 1.0.1
	Loaded Shaderpack: Insanity-Shaders-All-Versions
		Profile: ULTRA (+2 options changed by user)
	Flywheel Backend: Off
	Server Running: true
	Player Count: 1 / 8; [class_3222['RustVEVO'/550, l='ServerLevel[New World]', x=9.77, y=-60.00, z=1.69]]
	Data Packs: vanilla, Fabric Mods, $polymer-resources (incompatible), loadmyresources.hiddenpack (incompatible)
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.19.2

**Comment by MeatWheeze** [comment]
Thank you very much! I've been meaning to make a Discord but I haven't got round to it.
I'm able to reproduce the crash with Recipe Essentials and NEEPMeat. It's caused by some jank I wrote ages ago so that my machines would work with the Vanilla recipe system (similar to #5). The fix seems trivial, so I'll release a fixed version shortly.
