### ISSUE TITLE
version support

### ISSUE THREAD

**Issue by FrostBird347** [MeatWheeze/NeepMeat#7]
I noticed that this mod recently updated from 1.19.2 to 1.20.1.

Between the fact that the 1.20.1 jar shares the same version number as the previous 1.19.2 jar and the fact that the default branch is named "1.19.2/dev", one would assume you intend on supporting both 1.19.2 and 1.20.1.
However, both the lack of commits to the default branch since the last 1.19.2 version as well as the increased suffering that goes along with supporting multiple versions cast doubt on the possibility of future 1.19.2 support.

Are you able to provide clarification on this matter?

**Comment by MeatWheeze** [comment]
I intend to support both 1.19.2 and 1.20.1 for the immediate future with bug fixes and feature parity. Given the amount of work involved in supporting both versions, I may change my mind in the future. The jars for both versions have the same version to indicate that their feature sets should be the same. 
I have worked on the 1.19.2 branch a little but have not pushed the recent commits. I am very busy at the moment, so I will probably not be able to finish any releases in the next few weeks.

Hope this helps.

**Comment by FrostBird347** [comment]
Thanks for clarifying!
