### ISSUE TITLE
The mod makes stone blocks unobtainable

### ISSUE THREAD

**Issue by RushanM** [MeatWheeze/NeepMeat#9]
When this mod is in my tech modpack, any attempts to break stone blocks like stone and coal ore are futile, as firstly they break long with any tool (be it a netherite pickaxe) as if they were broken by hand, and secondly they drop nothing. This makes survival incredibly difficult and only creepers can help you blast some stone so you can make stone tools. When I remove the mod from the pack, everything goes back to normal. I don't think this is the intended behavior of the mod.

I'm using Fabric 0.15.7 on Minecraft 1.20.1.

The log is me creating a super flat world and putting a couple stones in it, then trying to break them with a diamond pickaxe.
[Game log 2024-3-30-7.txt](https://github.com/MeatWheeze/NeepMeat/files/14810451/Game.log.2024-3-30-7.txt)

**Comment by MeatWheeze** [comment]
Version 0.2.20 was released with a broken mineable/pickaxe.json file. Sorry about this. This was fixed in version 0.2.21:
https://modrinth.com/mod/neepmeat/version/0.2.21-beta+1.20.1
